import {EstruturaPaginaStyle, ConteudoPaginaStyle} from "./style"
import Head from 'next/head'
import Header from "./Header"
import Footer from "./Footer"


export default function EstruturaPagina(props){
    return(
        <>
            <Head>
                <title>PedroCeglia | Portifólio</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <EstruturaPaginaStyle>
                <div className="projeto-top-page"></div>
                <Header/>
                <ConteudoPaginaStyle>
                    {props.children}  
                </ConteudoPaginaStyle>
                <Footer/>
            </EstruturaPaginaStyle>
        </>

    )
}
